test_questions_filename = 'dataset/check_accuracy/questions.txt'
train_vocabulary_path = 'objects/train/vocabulary.pkl'
test_vocabulary_path = 'objects/test/vocabulary.pkl'
test_cbow_data_generator_path = 'objects/test/data_generators/cbow_data_generator.pkl'
test_n_gram_data_generator_path = 'objects/test/data_generators/n_gram_data_generator.pkl'
test_global_n_gram_data_generator_path = 'objects/test/data_generators/global_n_gram_data_generator.pkl'
train_cbow_data_generator_path = 'objects/train/data_generators/cbow_data_generator.pkl'
train_n_gram_data_generator_path = 'objects/train/data_generators/n_gram_data_generator.pkl'
train_global_n_gram_data_generator_path = 'objects/train/data_generators/global_n_gram_data_generator.pkl'
test_meta_lines_indices = []
test_questions_parser_path = 'objects/test/questions_parser.pkl'
train_questions_parser_path = 'objects/train/questions_parser.pkl'
batch_size = 8
USE_GPU = True
embedding_dim = 3
epochs = 25
window_size = 5
half_window_size = window_size // 2
train_questions_filename = 'dataset/check_accuracy/questions-words.txt'
train_meta_lines_indices = [0, 1, 582, 998]
train_corpus_storage_path = 'objects/train/corpus_storage.pkl'
test_corpus_storage_path = 'objects/train/corpus_storage.pkl'